language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
  - '6'
script:
  - npm run test:prod && npm run build
after_success:
## If you want to report test coverage to Coveralls
#  - npm run travis-deploy-once "npm run report-coverage"

## If you want to deploy generated docs to github
#  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run deploy-docs"; fi

## If you want to deploy library to public github
#  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
